name: go-llama31
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy>=1.24.0
      - transformers>=4.42.0
      - tokenizers>=0.19.0
      - torch>=2.3.0
      - tqdm
      - accelerate>=0.31.0
      - datasets>=2.20.0
